version: 2.1

executors:
  php:
    docker:
      - image: cimg/php:8.3.30
    resource_class: small

jobs:
  php-test: 
    executor: php
    steps:
      - run:
          name: php extract script
          command: |
            sudo docker-php-source extract
      - run:
          name: run php docker php-test
          command: |
            sudo docker-php-ext-install zip bcmath pdo_mysql

workflows:
  docker-check-workflow:
    jobs:
      - php-test